config/routes.rb
Rails.application.routes.draw do
  get "ingredient/index"
  get "ingredient/show"
  get "ingredient/new"
  get "ingredient/create"
  get "home/index"
  devise_for :users
  resources :recipes, :ingredients

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit({ roles: [] }, :email, :password, :password_confirmation)
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def recipes
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  require "byebug"

  def index
    @ingredient = Ingredient.new
    @recipes = []
  end

  def new
    @ingredient = Ingredient.new
    @recipes = []
  end
  
  def create
    @ingredient = Ingredient.new
    @recipes = []

    ingredient_names = params[:ingredient_names].to_s.split(',').map(&:strip).reject(&:empty?)

    ingredient_names.each do |name|
      matching_recipes = Recipe.joins(:ingredients).where("ingredients.name = ?", name)
      @recipes.concat(matching_recipes).uniq!
    end

    render :show

    rescue ActiveRecord::RecordNotFound => e
    render file: File.join(Rails.root, "public", "400.html"), layout: false, status: 400

  end

  def show
    @recipes
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      # Handle ingredients
      ingredient_names = params[:ingredient_names].to_s.split(',').map(&:strip).reject(&:empty?)

      ingredient_names.each do |name|
        ingredient = Ingredient.find_or_create_by(name: name)
        @recipe.ingredients << ingredient unless @recipe.ingredients.include?(ingredient)
      end

      redirect_to @recipe
    else
      render :new
    end

  rescue ActiveRecord::RecordNotUnique => e
    render file: File.join(Rails.root, "public", "400.html"), layout: false, status: 400

  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def list
    @recipes = nil
    @ids = Ingredient.find(params[:name])
    @ids.each do |id|
      @recipes.push(RecipeIngredient.find(params[:id]))
    end
  end

  private def recipe_params
    params.require(:recipe).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
<html>
    <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet"> 
    </head>

    <h1 class="title">RecipeSearch</h1>
    <h2 class="caption">Find the perfect recipe for you!</h2>
    <div class="submit">
        <%= link_to "Add ingredients", ingredients_path, class: "ingredient_button" %>
    </div>
</html>

app/views/home/list.html.erb
<head>
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<div class="show">
    <h2 class="caption">Here are the matching recipes:</h2>

    <h3 class="recipe"> <%= @recipe.name.upcase %> </h3><br>
        <ul>
            <% @recipe.ingredients.each do |ingredient| %>
                <li class="ingredient"><%= ingredient.name %></li>
            <% end %>
        </ul>
    <%= link_to "Add more ingredients", new_recipe_path, class: "ingredient_button" %>
</div>

app/views/ingredients/create.html.erb
<h1>Ingredient#create</h1>
<p>Find me in app/views/ingredient/create.html.erb</p>

app/views/ingredients/index.html.erb
<html>
    <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
        <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    </head>

    <h1 class="title">RecipeSearch</h1>
    <h2 class="caption">Find the perfect recipe for you!</h2>
    <div class="submit">
        <%= form_for @ingredient do |f| %>
            <%= text_field_tag :ingredient_names, "", placeholder: "salt, pepper, egg", class: "enter_ingredient" %>
            <%= f.submit "Submit Ingredients", class: "ingredient_button" %>
        <% end %>
    </div>
</html>

app/views/ingredients/new.html.erb
<h1>Ingredient#new</h1>
<p>Find me in app/views/ingredient/new.html.erb</p>

app/views/ingredients/show.html.erb
<head>
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<div class="show">
    <% if @recipes && @recipes.any? %>
        <h2 class="caption">Here are your matching recipes:</h2>
        <% @recipes.each do |recipe| %>
            <div class="full_recipe">
                <h3 class="recipe_name"> <%= recipe.name.upcase %> </h3>
                <% recipe.ingredients.each do |ingredient| %>
                    <h3 class="ingredient">- <%= ingredient.name %></h3>
                <% end %>
            </div>
        <% end %>
    <% else %>
        <h2 class="caption">There were no matching recipes,<br>try different ingredients</h2>
    <% end %>
    <%= link_to "Add more ingredients", ingredients_path, class: "ingredient_button" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Recipe Finder" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete,
        class: "log"
      ) %>
    <% end %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<p class="title">Index</p>

app/views/recipes/new.html.erb
<head>
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet"> 
</head>

<%= form_for(@recipe) do |f| %>
  <div class="field">
    <%= f.label :name, "Recipe Name" %><br />
    <%= f.text_field :name, placeholder: "fried egg" %>
  </div>

  <div class="field">
    <%= label_tag :ingredient_names, "Ingredients" %><br />
    <%= text_field_tag :ingredient_names, "", placeholder: "salt, pepper, egg" %>
  </div>

  <div class="actions">
    <%= f.submit "Add Recipe" %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<head>
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<div class="show">
    <h2 class="caption">Here is your new recipe:</h2>
    <div class="full_recipe">
        <h3 class="recipe_name"> <%= @recipe.name.upcase %> </h3>
        <% @recipe.ingredients.each do |ingredient| %>
            <h3 class="ingredient">- <%= ingredient.name %></h3>
        <% end %>
    </div>
    <%= link_to "Add more ingredients", new_recipe_path, class: "ingredient_button" %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %>
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %>
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %>
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %>
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %>
  <% end %>
<% end %>